#!/usr/bin/python3.12
import datetime
from pathlib import Path

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
Path("/tmp/xbo_hello_world.txt").write_text(f"hello world from xbo: {now}\n")
